---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[zlib]
  - recipe[zlib::dev]
